src/OC/PlatformBundle/Entity/Image.php
<?php

declare(strict_types=1);

namespace OC\PlatformBundle\Entity;

use OC\PlatformBundle\Model\ImageInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Class Image
 * @package OC\PlatformBundle\Entity
 */
class Image implements ImageInterface
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var string
     */
    protected $url;

    /**
     * @var string
     */
    protected $alt;

    /**
     * @var UploadedFile
     */
    protected $file;

    /**
     * @var string
     */
    protected $tempFilename;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * @return string
     */
    public function getAlt(): ?string
    {
        return $this->alt;
    }

    /**
     * @param string $alt
     */
    public function setAlt(string $alt): void
    {
        $this->alt = $alt;
    }

    /**
     * @return UploadedFile
     */
    public function getFile(): ?UploadedFile
    {
        return $this->file;
    }

    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        if (null !== $this->url) {
            $this->tempFilename = $this->url;

            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @return string
     */
    public function getUploadDir(): string
    {
        return 'uploads/img';
    }

    /**
     * @return string
     */
    public function getUploadRootDir(): string
    {
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    /**
     *
     */
    public function preUpload(): void
    {
        if (null === $this->file) {
            return;
        }

        $this->url = $this->file->guessExtension();

        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     *
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }

        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        $this->file->move(
            $this->getUploadRootDir(),
            $this->id . '.' . $this->url
        );
    }

    /**
     *
     */
    public function preRemoveUpload(): void
    {
        $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->url;
    }

    /**
     *
     */
    public function removeUpload(): void
    {
        if (file_exists($this->tempFilename)) {
            unlink($this->tempFilename);
        }
    }

    /**
     * @return string
     */
    public function getWebPath():string
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/OC/PlatformBundle/Form/AdvertType.php
<?php

namespace OC\PlatformBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

/**
 * Class AdvertType
 * @package OC\PlatformBundle\Form
 */
class AdvertType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('published')
            ->add('date', DateTimeType::class)
            ->add('title', TextType::class)
            ->add('author', TextType::class)
            ->add('content', TextareaType::class)
            ->add('image', ImageType::class, array('required' => false))
            ->add('save', SubmitType::class)
            ->add('categories', EntityType::class, array(
                'class'        => 'OCPlatformBundle:Category',
                'choice_label' => 'name',
                'multiple'     => true,
            ));
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) {
                $advert = $event->getData();


                if (null === $advert) {
                    return;
                }

                if (!$advert->getPublished() || null === $advert->getId()) {
                    $event->getForm()->add('published', CheckboxType::class, array('required' => false));
                } else {
                    $event->getForm()->remove('published');
                }
            }
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OC\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * @return null|string
     */
    public function getBlockPrefix(): string
    {
        return 'oc_platformbundle_advert';
    }
}

src/OC/PlatformBundle/Controller/AdvertController.php
<?php

declare(strict_types=1);

namespace OC\PlatformBundle\Controller;

use OC\PlatformBundle\Entity\Advert;
use OC\PlatformBundle\Event\MessagePostEvent;
use OC\PlatformBundle\Event\PlatformEvents;
use OC\PlatformBundle\Form\AdvertEditType;
use OC\PlatformBundle\Form\AdvertType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * Class AdvertController
 * @package OCPlatformBundle\Controller
 */
class AdvertController extends Controller
{

    /**
     * @param $page
     *
     * @return Response
     */
    public function indexAction($page): response
    {
        if ($page < 1) {
            throw new NotFoundHttpException('Page "' . $page . '" inexistante.');
        }

        $nbPerPage = 3;

        $listAdverts = $this->getDoctrine()
            ->getManager()
            ->getRepository('OCPlatformBundle:Advert')
            ->getAdverts($page, $nbPerPage);

        $nbPage = ceil(count($listAdverts) / $nbPerPage);

        return $this->render('OCPlatformBundle:Advert:index.html.twig', [
            'listAdverts' => $listAdverts,
            'nbPages'     => $nbPage,
            'page'        => $page
        ]);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function viewAction(int $id): response
    {
        $em = $this->getDoctrine()->getManager();

        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id " . $id . " n'existe pas.");
        }

        $listApplications = $em
            ->getRepository('OCPlatformBundle:Application')
            ->findBy(['advert' => $advert]);

        $listAdvertSkills = $em
            ->getRepository('OCPlatformBundle:AdvertSkill')
            ->findBy(['advert' => $advert]);


        return $this->render('OCPlatformBundle:Advert:view.html.twig', [
            'advert'           => $advert,
            'listApplications' => $listApplications,
            'listAdvertSkills' => $listAdvertSkills,
        ]);
    }

    /**
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */

    public function addAction(Request $request)
    {

        if (!$this->get('security.authorization_checker')->isGranted('ROLE_AUTEUR')) {
            throw new AccessDeniedException('Accès limité aux auteurs.');
        }
        $advert = new Advert();
        $form   = $this->createForm(AdvertType::class, $advert);


        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $event = new MessagePostEvent($advert->getContent(), $this->getUser());

            $this->get('event_dispatcher')->dispatch(PlatformEvents::POST_MESSAGE, $event);

            $advert->setContent($event->getMessage());

            $em = $this->getDoctrine()->getManager();

            $em->persist($advert);
            $em->flush();

            $this->addFlash('notice', 'Annonce bien enregistrée.');

            return $this->redirectToRoute('oc_platform_view', ['id' => $advert->getId()]);
        }

        return $this->render('OCPlatformBundle:Advert:add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param int     $id
     * @param Request $request
     *
     * @return Response
     */

    public function editAction(int $id, Request $request): response
    {
        $em     = $this->getDoctrine()->getManager();
        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id " . $id . " n'existe pas.");
        }

        $form = $this->createForm(AdvertEditType::class, $advert);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $em->persist($advert);
            $em->flush();

            $this->addFlash('notice', 'Annonce bien modifiée.');

            return $this->redirectToRoute('oc_platform_view', ['id' => $advert->getId()]);
        }


        return $this->render('OCPlatformBundle:Advert:add.html.twig', [

            'advert' => $advert,
            'form'   => $form->createView(),

        ]);
    }

    /**
     * @param int     $id
     * @param Request $request
     *
     * @return Response
     */
    public function deleteAction(int $id, Request $request): response
    {

        $em     = $this->getDoctrine()->getManager();
        $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id " . $id . " n'existe pas.");
        }

        $form = $this->get('form.factory')->create();

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em->remove($advert);
            $em->flush();

            $this->addFlash('info', "L'annonce a bien été supprimée.");

            return $this->redirectToRoute('oc_platform_home');
        }

        return $this->render('OCPlatformBundle:Advert:delete.html.twig', [
            'advert' => $advert,
            'form'   => $form->createView(),
        ]);
    }

    /**
     * @param $limit
     *
     * @return Response
     */
    public function menuAction($limit): response
    {
        $em          = $this->getDoctrine()->getManager();
        $listAdverts = $em->getRepository('OCPlatformBundle:Advert')->findBy(
            [],
            ['date' => 'desc'],
            $limit,
            0
        );

        return $this->render('OCPlatformBundle:Advert:menu.html.twig', [
            'listAdverts' => $listAdverts
        ]);
    }

    /**
     * @param $days
     *
     * @return Response
     */
    public function purge($days)
    {
        $listAdverts = $this->getDoctrine()
            ->getManager()
            ->getRepository('OCPlatformBundle:Advert')
            ->deleteAdvertByDaysPassed($days);

        return $this->render('OCPlatformBundle:Advert:index.html.twig', [
            'listAdverts' => $listAdverts,
        ]);
    }

    /**
     * @return Response
     */
    public function testAction()
    {
        $advert = new Advert;

        $advert->setDate(new \Datetime());  // Champ « date » OK
        $advert->setTitle('titret');           // Champ « title » incorrect : moins de 10 caractères
        $advert->setContent('blabla');    // Champ « content » incorrect : on ne le définit pas
        $advert->setAuthor('Abb');            // Champ « author » incorrect : moins de 2 caractères

        // On récupère le service validator
        $validator  = $this->get('validator');
        $listErrors = $validator->validate($advert);
        $content    = count($listErrors) > 0 ? (string)$listErrors : "L'annonce est valide !";

        return new Response($content);
    }

    /**
     * @param $name
     *
     * @return Response
     */
    public function translationAction(string $name)
    {
        return $this->render('OCPlatformBundle:Advert:translation.html.twig', [
            'name' => $name
        ]);
    }
}

src/OC/PlatformBundle/Resources/views/Advert/add.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Créer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Créer une annonce</h2>

    {{ include("OCPlatformBundle:Advert:form.html.twig") }}

    <p>
      Vous créer une annonce
    </p>

    <p>
        {{ form_rest(form) }}
        <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
    </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/bye.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Bienvenue sur ma première page avec OpenClassrooms !</title>
</head>
<body>
<h1>Bye {{ nom }} !</h1>

<p>
   A très bientôt
</p>
</body>
</html>

src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Supprimer une annonce</h2>

    <p>
        Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
    </p>

    <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        <input type="submit" value="Supprimer" class="btn btn-danger" />
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Modifier une annonce</h2>

    {{ include("OCPlatformBundle:Advert:form.html.twig") }}

    <p>
        Vous éditez une annonce déjà existante, merci de ne pas changer
        l'esprit général de l'annonce déjà publiée.
    </p>

    <p>
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
    </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/form.html.twig
<h3>Formulaire d'annonce</h3>

<div class="well">
    {{ form(form) }}
    {# src/OC/PlatformBundle/Resources/views/Advert/form.html.twig #}

    {# Le formulaire reste globalement le même,
       On ne rajoute que le champ catégorie et le lien pour en ajouter #}
    <div class="well">
        {# ... #}

        {{ form_row(form.categories) }}
        <a href="#" id="add_category" class="btn btn-default">Ajouter une catégorie</a>

        {# ... #}
    </div>

    {# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google
       mais si vous l'avez en local, changez simplement l'adresse. #}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    {# Voici le script en question : #}
    <script type="text/javascript">
        $(document).ready(function() {
            // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
            var $container = $('div#oc_platformbundle_advert_categories');

            // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
            var index = $container.find(':input').length;

            // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
            $('#add_category').click(function(e) {
                addCategory($container);

                e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                return false;
            });

            // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
            if (index == 0) {
                addCategory($container);
            } else {
                // S'il existe déjà des catégories, on ajoute un lien de suppression pour chacune d'entre elles
                $container.children('div').each(function() {
                    addDeleteLink($(this));
                });
            }

            // La fonction qui ajoute un formulaire CategoryType
            function addCategory($container) {
                // Dans le contenu de l'attribut « data-prototype », on remplace :
                // - le texte "__name__label__" qu'il contient par le label du champ
                // - le texte "__name__" qu'il contient par le numéro du champ
                var template = $container.attr('data-prototype')
                    .replace(/__name__label__/g, 'Catégorie n°' + (index+1))
                    .replace(/__name__/g,        index)
                ;

                // On crée un objet jquery qui contient ce template
                var $prototype = $(template);

                // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
                addDeleteLink($prototype);

                // On ajoute le prototype modifié à la fin de la balise <div>
                $container.append($prototype);

                // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
                index++;
            }

            // La fonction qui ajoute un lien de suppression d'une catégorie
            function addDeleteLink($prototype) {
                // Création du lien
                var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

                // Ajout du lien
                $prototype.append($deleteLink);

                // Ajout du listener sur le clic du lien pour effectivement supprimer la catégorie
                $deleteLink.click(function(e) {
                    $prototype.remove();

                    e.preventDefault(); // évite qu'un # apparaisse dans l'URL
                    return false;
                });
            }
        });
    </script>
</div>

src/OC/PlatformBundle/Resources/views/Advert/index.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <h2>Liste des annonces</h2>

    <ul>
        {% for advert in listAdverts %}
            <li>
                <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
                    {{ advert.title }}
                </a>
                par {{ advert.author }},
                le {{ advert.date|date('d/m/Y') }}
            </li>
        {% else %}
            <li>Pas (encore !) d'annonces</li>
        {% endfor %}
    </ul>

    <ul class="pagination">
        {% for p in range(1, nbPages) %}
            <li{% if p == page %} class="active"{% endif %}>
                <a href="{{ path('oc_platform_home', {'page': p}) }}">{{ p }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig
<ul class="nav nav-pills nav-stacked">
    {% for advert in listAdverts %}
        <li>
            <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
                {{ advert.title }}
            </a>
        </li>
    {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/translation.html.twig
<html>
    <body>
        {{ 'hello'|trans({'%name%': name}) }}
    </body>
</html>

src/OC/PlatformBundle/Resources/views/Advert/view.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}
    {% if advert.image is not null %}

        <img <img
            src="{{ asset(advert.image.uploadDir ~ '/' ~ advert.image.id ~ '.' ~ advert.image.url) }}"
            alt="{{ advert.image.alt }}"
    />>

    {% endif %}
    <h2>{{ advert.title }}</h2>

    <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }} , </i>
    {% if not advert.categories.empty %}
        <p>
            Cette annonce est parue dans les catégories suivantes :
            {% for category in advert.categories %}
                {{ category.name }}{% if not loop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% endif %}
    {% if listAdvertSkills|length > 0 %}
        <div>
            Cette annonce requiert les compétences suivantes :
            <ul>
                {% for advertSkill in listAdvertSkills %}
                    <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div class="well">
        {{ advert.content }}
    </div>

    <p>
        <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
        <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier l'annonce
        </a>
        <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer l'annonce
        </a>
    </p>
    {% for application in listApplications %}
        <i>{{ application.author }}, {{ application.date|date('d/m/Y') }}</i>
        <p>{{ application.content }}</p>
    {% endfor %}

{% endblock %}